name: directfarm
description: "directfarm"
publish_to: 'none'
version: 0.1.3+7

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.4
  flutter_localization: ^0.3.3
  permission_handler: ^12.0.1
  webview_flutter: ^4.13.0
  firebase_core: ^4.3.0
  flutter_svg: ^2.0.10
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/logo/icon.png
